/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { UserForAuthenticationDto } from '../model/userForAuthenticationDto';
import { UserForRegistrationDto } from '../model/userForRegistrationDto';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import jwtDecode from 'jwt-decode';


@Injectable()
export class AuthenticationService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    // tslint:disable-next-line:max-line-length
    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        this.basePath = this.configuration.basePath;
        if (configuration) {
            this.configuration = configuration;
        }
    }
    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiAuthenticationLoginPost(body?: UserForAuthenticationDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    // tslint:disable-next-line:max-line-length
    public apiAuthenticationLoginPost(body?: UserForAuthenticationDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    // tslint:disable-next-line:max-line-length
    public apiAuthenticationLoginPost(body?: UserForAuthenticationDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    // tslint:disable-next-line:max-line-length
    public apiAuthenticationLoginPost(body?: UserForAuthenticationDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys.Authorization) {
            headers = headers.set('Authorization', this.configuration.apiKeys.Authorization);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post', `${this.basePath}/api/authentication/login`,
            {
                body,
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }

    /**
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiAuthenticationPost(body?: UserForRegistrationDto, observe?: 'body', reportProgress?: boolean): Observable<any>;
    // tslint:disable-next-line:max-line-length
    public apiAuthenticationPost(body?: UserForRegistrationDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiAuthenticationPost(body?: UserForRegistrationDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiAuthenticationPost(body?: UserForRegistrationDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys.Authorization) {
            headers = headers.set('Authorization', this.configuration.apiKeys.Authorization);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('post', `${this.basePath}/api/authentication`,
            {
                body,
                withCredentials: this.configuration.withCredentials,
                headers,
                observe,
                reportProgress
            }
        );
    }
    // tslint:disable-next-line:typedef
    getToken() {
        const token = JSON.parse(localStorage.getItem('access_token') || '{}');
        return token.token;
    }
    get isLoggedIn(): boolean {
        const authToken = localStorage.getItem('access_token');
        return (authToken !== null) ? true : false;
    }
    get isAdministrator(): boolean {
        const authToken = localStorage.getItem('access_token');
        if (authToken !== null) {
            const decoded: any = jwtDecode(authToken);
            return (decoded.roles === 'Administrator') ? true : false;
        }
        return false;
    }
    // tslint:disable-next-line:typedef
    doLogout() {
        localStorage.removeItem('access_token');
    }
}
