version: '3.4'

services:
  caloriestracker.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"
  db:
    ports:
      - "1433:1433" 