version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: Db/Dockerfile
    volumes:
      - ./Db:/usr/src/app 
  backend:
    image: ${DOCKER_REGISTRY-}caloriestrackerapi
    build:
      context: .
      dockerfile: CaloriesTracker.Api/Dockerfile
    depends_on:
      - db
  front:
    image: clientapp
    build:
      context: .
      dockerfile: CaloriesTracker.Api/ClientApp/Dockerfile
    depends_on:
       - backend
    