version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:50
    ports:
      - "5001:5000"
  db:
    ports:
      - "1433:1433" 
  front:
    ports:
      - "8080:80" 