version: '3.4'

services:
  gateway:
    ports:
      - "5000:80" 
  eating_microservice:
    ports:
      - "5006:80"
  recipe_microservice:
    ports:
      - "5005:80"
  activity_microservice:
    ports:
      - "5004:80"
  user_microservice:
    ports:
      - "5003:80"
  exercise_microservice:
    ports:
      - "5002:80" 
  ingredient_microservice:
    ports:
      - "5001:80" 
  db:
    ports:
      - "1433:1433" 
  #front:
  #  ports:
  #    - "8080:80" 