version: '3.4'

services:
  db:
    build:
      context: .
      dockerfile: Db/Dockerfile
    volumes:
      - ./Db:/usr/src/app 
  caloriestracker.api:
    image: ${DOCKER_REGISTRY-}caloriestrackerapi
    build:
      context: .
      dockerfile: CaloriesTracker.Api/Dockerfile
    depends_on:
      - db