/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type CaseTransformType = 0 | 1 | 2 | 3;

export const CaseTransformType = {
    NUMBER_0: 0 as CaseTransformType,
    NUMBER_1: 1 as CaseTransformType,
    NUMBER_2: 2 as CaseTransformType,
    NUMBER_3: 3 as CaseTransformType
};