/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Eating } from './eating';
import { Ingredient } from './ingredient';

export interface IngredientEating { 
    id?: string;
    ingredientId?: string;
    ingredient?: Ingredient;
    eatingId?: string;
    eating?: Eating;
    grams?: number;
}