/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Activity } from './activity';
import { Exercise } from './exercise';

export interface ActivityExercise { 
    id?: string;
    exerciseId?: string;
    exercise?: Exercise;
    activityId?: string;
    activity?: Activity;
    numberOfRepetitions?: number;
    numberOfSets?: number;
}