/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelObject } from './modelObject';
import { OperationType } from './operationType';

export interface ExerciseForUpdateDtoOperation { 
    operationType?: OperationType;
    value?: ModelObject;
    path?: string;
    op?: string;
    from?: string;
}