/**
 * Calorie Tracker API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: vladimir.lyashko02@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CaseTransformType } from './caseTransformType';
import { IContractResolver } from './iContractResolver';
import { IngredientForUpdateDtoOperation } from './ingredientForUpdateDtoOperation';

export interface IngredientForUpdateDtoJsonPatchDocument { 
    readonly operations?: Array<IngredientForUpdateDtoOperation>;
    contractResolver?: IContractResolver;
    caseTransformType?: CaseTransformType;
}